name: flude-check
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  flude:
    runs-on: ubuntu-latest
    steps:
      - uses: Flude-team/flude-action@main
        with:
          api-base-url: https://flude-worker-controlplane-bfsnlsrm2a-uc.a.run.app
          api-token: ${{ secrets.FLUDE_API_TOKEN }}
